remote_theme: just-the-docs/just-the-docs
title: Mehul's homepage
description: Bookmark this to keep an eye on my project updates!

url: https://magensium2400.github.io/

# External navigation links
nav_external_links:
  - title: nihelp
    url: https://magnesium2400.github.io/nihelp
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

    
